version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /demo
    schedule:
      interval: daily
    allow:
      - dependency-type: production
      - dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10