version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /demo
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /.github/actions/install-graphics-driver
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /.github/actions/prepare-build-env
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /.github/actions/post-build-env
    schedule:
      interval: daily
    target-branch: "develop"
    open-pull-requests-limit: 10