[package]
name = "wgpu-layers"
version = "0.1.0"
authors = ["Paul Lange <paul.lange@data-experts.de>"]
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
log = "0.4.17"
wgpu = "0.13.1"
rayon = "1.5.3"
geo-types = "0.7.6"
bytemuck = "1.10.0"
earcutr = "0.2.0"
prost = { version = "0.10.4", default-features = false, features = ["prost-derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.81"
wasm-bindgen-futures = "0.4.31"
wasm-bindgen-rayon = "1.0.3"
console_log = { version = "0.2.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.58", features = [
  "OffscreenCanvas"
]}
# https://github.com/Amanieu/parking_lot/issues/269
parking_lot_core = "=0.8.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.2.5"
env_logger = "0.9.0"
winit = "0.26.1"

[build-dependencies]
prost-build = "0.10.4"

[profile.release]
opt-level = "s"
