[package]
name = "wgpu-layers"
version = "0.1.0"
authors = ["Paul Lange <paul.lange@data-experts.de>"]
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.17"
wgpu = "0.14.0"
rayon = "1.5.3"
futures = "0.3.24"
lazy_static = "1.4.0"
geo-types = "0.7.7"
bytemuck = "1.12.1"
bytemuck_derive = "1.2.1"
earcutr = "0.3.0"
prost = { version = "0.11.0", default-features = false, features = ["prost-derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-bindgen-rayon = "1.0.3" # alternative https://github.com/chemicstry/wasm_thread
console_log = { version = "0.2.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.60", features = [
  "OffscreenCanvas",
  "HtmlElement", # from here all features are for integrationtests
  "CssStyleDeclaration",
  "HtmlCanvasElement",
  "FileReader",
  "Blob"
]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.2.5"
env_logger = "0.9.1"
winit = "0.27.4"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
include-base64 = "0.1.0"
js-sys = "0.3.60"

[build-dependencies]
prost-build = "0.11.1"

[profile.release]
opt-level = "s"
lto = true