[package]
name = "wgpu-layers"
version = "0.1.0"
description = "WebGPU mapping renderer for OpenLayers"
authors = ["Paul Lange <paul.lange@data-experts.de>"]
repository = "https://github.com/codeart1st/wgpu-layers"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
multithreaded = []

[dependencies]
log = "0.4.18"
wgpu = "0.16.1"
rayon = "1.7.0"
futures = "0.3.27"
geo-types = "0.7.9"
bytemuck = "1.13.1"
bytemuck_derive = "1.4.0"
earcutr = "0.4.2"
glam = { version = "0.24.0", default-features = false, features = ["libm", "bytemuck"] }
prost = { version = "0.11.9", default-features = false, features = ["prost-derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-rayon = "1.0.3" # alternative https://github.com/chemicstry/wasm_thread
console_log = { version = "1.0.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.63", features = [
  "OffscreenCanvas",
  "HtmlElement", # from here all features are for integrationtests
  "CssStyleDeclaration",
  "HtmlCanvasElement",
  "FileReader",
  "Blob"
]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3.0"
env_logger = "0.10.0"
winit = "0.28.6"

[dev-dependencies]
wasm-bindgen-test = "0.3.36"
pdqhash = "0.1.1"
js-sys = "0.3.63"

[build-dependencies]
prost-build = "0.11.9"

[profile.release]
opt-level = "s"
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false # version in wasm-pack is to old for simd128