[package]
name = "wgpu-layers"
version = "0.1.0"
authors = ["Paul Lange <paul.lange@data-experts.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
log = "0.4.14"
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
rayon = "1.5.1"
geo-types = "0.7.3"
bytemuck = "1.9.0"
earcutr = "0.2.0"
prost = { version = "0.10.0", default-features = false, features = ["prost-derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
wasm-bindgen-rayon = "1.0.3"
console_log = { version = "0.2.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.56", features = [
  "OffscreenCanvas"
]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.2.5"
env_logger = "0.9.0"
winit = "0.26.1"

[build-dependencies]
prost-build = "0.10.0"

[profile.release]
opt-level = "s"
