[package]
name = "wgpu-layers"
version = "0.1.0"
authors = ["Paul Lange <paul.lange@data-experts.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
log = "0.4.14"
wgpu = "0.12.0"
rayon = "1.5.1"
geo-types = "0.7.2"
bytemuck = "1.7.3"
earcutr = "0.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
wasm-bindgen-rayon = "1.0.3"
console_log = { version = "0.2.0", optional = true }
web-sys = { version = "0.3.56", features = [
  "OffscreenCanvas"
]}

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.2.5"
env_logger = "0.9.0"
winit = "0.26.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.29"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
