name: Install graphics driver

runs:
  using: "composite"
  steps:
    - name: Install mesa dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:oibaf/graphics-drivers -y
        sudo apt-get install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
