name: Install graphics driver
description: Ensures that all necessary Mesa libraries are installed

runs:
  using: "composite"
  steps:
    - name: Install mesa dependencies
      shell: bash
      run: sudo apt-get update -qq && sudo apt-get install -y libegl1-mesa mesa-vulkan-drivers xvfb
