export const READY = 'ready'
export const STARTED = 'started'
export const CANVAS = 'canvas'
export const FRAME_STATE = 'frame-state'
export const RENDERED = 'rendered'
export const PBF_DATA = 'pbf-data'